"""Weekly career progress report PDF."""

from __future__ import annotations

import base64
import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, HRFlowable, ListFlowable, ListItem

PRIMARY = colors.HexColor("#4F46E5")
DARK = colors.HexColor("#0F172A")
MUTED = colors.HexColor("#475569")


def _safe(text: Any) -> str:
    if text is None:
        return ""
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").strip()


def build_weekly_report_pdf(data: dict[str, Any]) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.7 * inch,
    )
    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "WRTitle",
        parent=styles["Heading1"],
        fontSize=20,
        textColor=DARK,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    h2 = ParagraphStyle(
        "WRH2",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=PRIMARY,
        spaceBefore=14,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    body = ParagraphStyle(
        "WRBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=DARK,
    )
    muted = ParagraphStyle(
        "WRMuted",
        parent=styles["Normal"],
        fontSize=9,
        textColor=MUTED,
        spaceAfter=8,
    )

    story: list[Any] = []
    story.append(Paragraph("CareerGPS AI — Weekly Report", title))
    story.append(
        Paragraph(
            f"{_safe(data.get('target_role') or data.get('career_path'))} · Career Operating System",
            muted,
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=12))

    score = data.get("career_score", 0)
    delta = data.get("weekly_delta", 0)
    story.append(Paragraph("Career Score", h2))
    story.append(
        Paragraph(
            f"<b>{score}</b> (previous {data.get('previous_score', score)}) · "
            f"Weekly change: {'+' if delta >= 0 else ''}{delta} · "
            f"Monthly change: {data.get('monthly_delta', 0)}",
            body,
        )
    )

    story.append(Paragraph("Progress Snapshot", h2))
    story.append(
        Paragraph(
            f"Roadmap {data.get('roadmap_progress', 0)}% · "
            f"Learning hours {data.get('learning_hours', 0)} "
            f"(this week {data.get('weekly_hours', 0)}) · "
            f"Interview readiness {data.get('interview_readiness', 0)} · "
            f"Resume {data.get('resume_score', 0)} / ATS {data.get('ats_score', 0)}",
            body,
        )
    )

    achievements = data.get("achievements") or []
    if achievements:
        story.append(Paragraph("Achievements", h2))
        story.append(
            ListFlowable(
                [ListItem(Paragraph(_safe(a), body)) for a in achievements[:12]],
                bulletType="bullet",
                leftIndent=12,
            )
        )

    skills = data.get("skills_learned") or []
    if skills:
        story.append(Paragraph("Skills Learned", h2))
        story.append(
            ListFlowable(
                [ListItem(Paragraph(_safe(s), body)) for s in skills[:12]],
                bulletType="bullet",
                leftIndent=12,
            )
        )

    wins = data.get("recent_wins") or []
    if wins:
        story.append(Paragraph("This Week's Wins", h2))
        story.append(
            ListFlowable(
                [ListItem(Paragraph(_safe(w), body)) for w in wins[:10]],
                bulletType="bullet",
                leftIndent=12,
            )
        )

    story.append(Paragraph("Recommended Focus", h2))
    story.append(Paragraph(_safe(data.get("recommended_focus") or "Keep shipping"), body))

    story.append(Paragraph("Motivational Summary", h2))
    story.append(Paragraph(_safe(data.get("motivational_summary") or ""), body))

    story.append(Spacer(1, 18))
    story.append(Paragraph("Generated by CareerGPS AI", muted))

    doc.build(story)
    return buffer.getvalue()


def weekly_report_base64(data: dict[str, Any]) -> str:
    return base64.b64encode(build_weekly_report_pdf(data)).decode("ascii")
